### ISSUE TITLE
Request time tracking

### ISSUE THREAD

**Issue by Faboslav** [System-Glitch/goyave#100]
## Support

**Version:** v2.7.0

Hello there! I didn't find any events/hooks which i could use for tracking time and other things of request. I know that i can create middleware to do this, but is there a way to track time of the request?

**Comment by System-Glitch** [comment]
What do you mean exactly by "tracking time of the request"? Do you want to measure the time it takes for your app to respond?

**Comment by Faboslav** [comment]
Yeah, exactly that

**Comment by System-Glitch** [comment]
You can indeed use a middleware for that but that won't measure the real time between when the server received the request and when the response finished writing.

For this kind of measurement, you should probably use a benchmarker program and measure from the outside of your application.
