### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by System-Glitch** [System-Glitch/goyave#105]
## Proposal

To make rate limiting easier, a middleware could be developed. This middleware would use a new config entry making it possible to adjust the rate easily. The real goal is to make a basic rate limiter middleware, which would cover most cases and be easy to use, mostly to protect from attacks.

The middleware will have to correctly set the following headers, following this [IETF spec](https://tools.ietf.org/id/draft-polli-ratelimit-headers-03.html): 
- `RateLimit-Limit`: the rate limit ceiling
- `RateLimit-Remaining`: the number of requests left
- `RateLimit-Reset`: the number of seconds until the quota resets

*Note: the IETF spec doesn't use the `X-` header prefix, unlike popular APIs such as Github's. It would be worth making some research to know if it would be better to add the `X-` prefix or keep it as defined in the IETF spec.*

In case of cancelled request because of limiting, the middleware would be stopping (don't call `next()`) and would respond with the HTTP status `429 Too Many Requests`, in accordance with [`RFC 6585`](https://tools.ietf.org/html/rfc6585#section-4). The default status handler can be kept and developers will be able to define the behavior of their choice when a request is rate limited.

Limiting will be done using an in-memory storage directly implemented in the middleware. A simple map and a struct containing the user's information (IP, time frame, remaining requests) are probably more than enough. The storage **needs** to be **thread-safe**, as requests can be served in parallel.

The official go package [`golang.org/x/time/rate`](https://pkg.go.dev/golang.org/x/time/rate?tab=doc) could be used, but it would need to be extended a little bit to support multiple clients. We want to limit IPs that keep requesting the server, but not the other legitimate users.

I would like to start with a simple rate limiter, as mentioned above, but a more advanced rate limiter could be developed next to it later on. There is no design or clear requirements specification for it yet. For example, this advanced rate limiter could:
- work with authenticated users and add variable limits depending on a user plan
- be configured to count rates in relation to a route
- use an external storage driver instead of the in-memory one explained earlier (support the database for example)
- check the `X-Forwarded-For` and `X-Real-IP` headers if the application is running behind a reverse proxy
- and more?

Either way, this middleware **has to** be compliant with previously mentioned [IETF spec](https://tools.ietf.org/id/draft-polli-ratelimit-headers-03.html).

### Possible drawbacks

Rate limiting can have a slight impact of performance, and especially on memory usage if using in-memory storage. However, it is a mandatory feature for public APIs and well worth the upfront cost.

### Additional information

This issue is a feature proposal and is meant to be discussed.
It is also a good candidate if you want to contribute to the project.

**Comment by varunu28** [comment]
@System-Glitch Can I pick this up and start working on it? I plan to present a spec initially for the design and then move forward with the implementation.

**Comment by System-Glitch** [comment]
@varunu28 Sure, go ahead! Thank you very much!

**Comment by varunu28** [comment]
@System-Glitch Sorry for the delay on this. I will be starting with this. Here is my initial plan. 
 - The rate limiter sits before the request validation. (Doesn't make sense to validate the request if we are gonna timeout anyway)
 - Having an in memory map to track requests coming from an IP. Making the data structure thread safe.

I agree with making it an advanced rate limiter based on your points. My thought process is to start with a basic implementation and then advance on it by adding enhancements.

**Comment by System-Glitch** [comment]
No problem for the delay.

- As the rate limiter sits before the validation, make it a middleware. Validation is always executed last.
- The memory map (probably `sync.Map` ?) is exactly how I imagined it.

Start by thinking how it would be used by the developer. There are several options for this:
- Pass an options structure to the function creating the middleware
- Create a new configuration category so these settings can be more easily tweaked in the json config file
- Maybe there is a middle ground between the two?

Don't hesitate to contact me if you need any help or guidance. Thank you very much !

**Comment by System-Glitch** [comment]
@varunu28 Any news?
