### ISSUE TITLE
A real demo for benchmarks projects and to improve learning

### ISSUE THREAD

**Issue by frederikhors** [System-Glitch/goyave#108]
## Proposal

Your work on this project is amazing. I think it's the most accurate docs ever seen for a Go framework.

But I think it would also be nice to create a "real demo" repo both to learn even better the "best practices" for proper use and to use as a benchmark in the following projects:

- https://github.com/smallnest/go-web-framework-benchmark and
- https://www.techempower.com/benchmarks

And it's better for the author himself to use his framework for those benchmarks rather than someone who doesn't understand 100% how to best use it.

What do you think about it?

Thanks again for the wonderful work!

**Comment by System-Glitch** [comment]
A full example project would be nice indeed. It's currently lacking. Do you have ideas for a realistic context? I would prefer to make a project that makes sense.

I planned on writing a medium example for a basic application, that could be a commentary of this example project.

I've never took the time to write extensive benchmarks yet. The ones available in the repository are more at the unit-level. I've also been requested for a benchmark [here](https://github.com/the-benchmarker/web-frameworks/issues/2647). Writing all of them will take time and delay other features but that would probably help the framework get more attention.

**Comment by frederikhors** [comment]
> Do you have ideas for a realistic context? I would prefer to make a project that makes sense.

I have many ideas:

- https://github.com/gothinkster/realworld
- a backend app for a SPA (or mobile) frontend
- a fully GraphQL backend
- a gateway for [Backends for Frontends](https://microservices.io/patterns/apigateway.html)
- a microservices approach (I realize that is not the purpose of this framework, perhaps)

> I've also been requested for a benchmark here.

Great project!

> Writing all of them will take time and delay other features but that would probably help the framework get more attention.

Yeah, I know. All of this is just nice-to-have. :smile:

**Comment by System-Glitch** [comment]
Another benchmark merged here: https://github.com/smallnest/go-web-framework-benchmark/pull/99

**Comment by System-Glitch** [comment]
Work in progress realworld example: https://github.com/System-Glitch/goyave-realworld-example-app

**Comment by System-Glitch** [comment]
Still a work in progress but I am working on a example project: https://github.com/System-Glitch/goyave-blog-example

I am closing this issue for now, but I will continue trying to improve on that if I have the time.

**Comment by frederikhors** [comment]
Anything about GraphQL?

**Comment by System-Glitch** [comment]
Goyave is not designed with graphql in mind. It's a non-goal.
