### ISSUE TITLE
Benchmark framwork 

### ISSUE THREAD

**Issue by phamtai97** [System-Glitch/goyave#11]
Hi all.
Before using the framework I usually care about its performance. Have you tried this framework benchmark? 
You can refer here about benchmark: https://github.com/smallnest/go-web-framework-benchmark

**Comment by System-Glitch** [comment]
Hello, thank you for this. I will try and add the results to the readme and documentation.

**Comment by phamtai97** [comment]
I have some experience with benchmarks service, can I join this project?

**Comment by System-Glitch** [comment]
Sure! Feel free to open a PR.

**Comment by phamtai97** [comment]
Great!!!. I wil try do it.

**Comment by phamtai97** [comment]
Hi @System-Glitch 
What types of routers can Goyave support? Routes such as: "PUT", "DELETE", "OPTION", "GET" have params, ..... 
I see the example route "GET" on the README.

**Comment by System-Glitch** [comment]
All HTTP methods are supported. JSON bodies are supported (don't forget the `Content-Type` header) as well as url-encoded bodies (parsed using Go's standard library).

**Comment by phamtai97** [comment]
Yeah !!! 
I will write a test benchmark soon.

**Comment by System-Glitch** [comment]
@phamtai97 Any news?

**Comment by phamtai97** [comment]
Hi, I am sorry. I've been busy lately. I just review it and do it.

**Comment by phamtai97** [comment]
Hi @System-Glitch. You can help me check pull request [this](https://github.com/System-Glitch/goyave/pull/27).

**Comment by System-Glitch** [comment]
Closed for inactivity.
