### ISSUE TITLE
Laravel

### ISSUE THREAD

**Issue by pjebs** [System-Glitch/goyave#113]
Is this loosly based on PHP Laravel framework?

**Comment by System-Glitch** [comment]
I took a lot of inspiration from Laravel indeed, but the goal is not to make a Laravel clone in Go.

**Comment by pjebs** [comment]
You should integrate this pkg: https://github.com/joho/godotenv similar to laravel

**Comment by System-Glitch** [comment]
The configuration file is already able to load environment variables, but if you need `godotenv` for your project, you can add it easily. Just call `godotenv.Load()` before `goyave.Start()`.
