### ISSUE TITLE
Request extra-data or with context value

### ISSUE THREAD

**Issue by System-Glitch** [System-Glitch/goyave#117]
## Proposal

It is currently not possible to add extra data to requests other than using `request.Data` or `request.User`. `http.Request` has `WithContext()`, which allows to add a context (`WithValue()`) to it.

Extra data in requests would allow middleware to process data that is not part of the request's body.

### Implementation

The simplest solution would be to add a `map[string]interface{}` named `Extra` to the request structure. Initialize it empty to avoid memory usage.

### Possible drawbacks

`None`.

**Comment by gmgalvan** [comment]
Hello, can I take this task?

**Comment by System-Glitch** [comment]
@gmgalvan Hi, sure! Thank you very much for your help!
