### ISSUE TITLE
Documentation on Gorm migrations incorrect

### ISSUE THREAD

**Issue by vgough** [System-Glitch/goyave#12]
## Description

The Goyave summary of Gorm's migration is incorrect.  Gorm states that tables, columns, and indexes are create.  Goyave states that columns and indexes won't be created.

From the Gorm documentation:

`AutoMigrate will ONLY create tables, missing columns and missing indexes, and WON’T change existing column’s type or delete unused columns to protect your data.`

As written in Goyave:

`Automatic migrations only creates tables. Missing columns and indexes won't be created, modified columns won't be changed and unused columns won't be deleted.`

**Comment by System-Glitch** [comment]
It will be fixed in the next release. Thank you.
