### ISSUE TITLE
README of generated project to include /echo

### ISSUE THREAD

**Issue by devisions** [System-Glitch/goyave#14]
Hi,

I am evaluating this framework, and based on the journey I would also try to contribute. 😃 

Just one remark for the moment: since the generated project includes - besides the `/hello` - also a `/echo` implementation, a cURL example how to call it might help also. Something like this:
- a simple example:
  ```bash
  curl -G -w '\n' http://localhost:8080/echo -d text=abc123
  abc123
  $
  ```
- an example when space encoding is needed:
  ```bash
  $ curl -G -w '\n' http://localhost:8080/echo --data-urlencode 'text=abc 123'
  abc 123
  $
  ```

**Comment by System-Glitch** [comment]
Hello. Thank you for the suggestion! I will add it for the next release.
