### ISSUE TITLE
Failed to Handle CORS

### ISSUE THREAD

**Issue by ridwankustanto** [System-Glitch/goyave#19]
## Description
Version: v2.2.0
Commit: bc72e19
**Version:** v2.2.0  
**Environment:** Mac Catalina, go1.13.4

Hi, I just noticed this when I tried to consume API within my vuejs app, it always blocked by CORS. I did use package "github.com/rs/cors" on middleware, but still can't solve it. And it said "OPTIONS 405 (Method Not Allowed" which I guess I handled on middleware.

first, I tried manual way to handle cors through middleware:

    func EnableCORS(next goyave.Handler) goyave.Handler {
    
	return func(response *goyave.Response, request *goyave.Request) {

		(*response).Header().Set("Access-Control-Allow-Origin", "*")
		(*response).Header().Set("Access-Control-Allow-Methods", "POST, GET, OPTIONS, PUT, DELETE")
		(*response).Header().Set("Access-Control-Allow-Headers", "Accept, Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization")
		(*response).Header().Set("Content-Type", "application/json")
		(*response).Header().Set("Content-Type", "text/html; charset=utf-8")
		(*response).Header().Set("Access-Control-Allow-Credentials", "true")

		log.Println(request.Method())
		if (*request).Method() == "OPTIONS" {
			response.WriteHeader(http.StatusOK)
			return
		}

		next(response, request) // Pass to the next handler
	}

    }

And I tried to use this pkg too "github.com/rs/cors" on the route register:

    routers := router.Subrouter("/")
	middlewareCors := goyave.NativeMiddleware(func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			handler := cors.AllowAll().Handler(next)

			if r.Method == "OPTIONS" {
				w.WriteHeader(http.StatusOK)
				return
			}
			handler.ServeHTTP(w, r) // Don't call "next" if your middleware is blocking.
		})
	})
	routers.Middleware(middlewareCors)

But none of them can solve cors or handle Preflight request. Or I miss something...

Can you give me example of handling cors with goyave? That would be great.

Thanks!

**Comment by System-Glitch** [comment]
Hello. Can you show me your route definition? Be sure to include the `OPTIONS` method.

```go
router.Route("GET|OPTIONS", "/hello", hello.SayHi, nil)
```

A better support for the `OPTIONS` method and CORS is already planned for future releases.

**Comment by ridwankustanto** [comment]
Hi! Oh I see, I can't find that approach on the documentation. Anyway, at the moment, finally, I could make it works. This is my route before implemented OPTIONS:

    routers.Route("POST|OPTIONS", "/auth/login", auth.LoginUser, nil)

and I change it to:

    routers.Route("POST|OPTIONS", "/auth/login", auth.LoginUser, nil)

plus I add middleware that handle cors like I mentioned on above.

    routers := router.Subrouter("/")
    routers.Middleware(middleware.EnableCORS)

Thanks, mate!
