### ISSUE TITLE
Template rendering

### ISSUE THREAD

**Issue by OpoOpo** [System-Glitch/goyave#20]
Hi,
I am wondering if there is a method like `response.JSON()` for template rendering from package `text/template`
for example like
```response.Render(http.StatusOK, "template", &dataStructure)```

Thank you.

**Comment by System-Glitch** [comment]
Hello,

For the moment there isn't such function, as the framework is mainly focused on APIs. But if you're interested in the feature, feel free to open a PR or a feature request.

**Comment by OpoOpo** [comment]
Thank you for the response,
I would like it as a feature request can you change the type of this issue on feature request?
