### ISSUE TITLE
Custom HTTP request error handler such as 404 handler etc

### ISSUE THREAD

**Issue by ervan23** [System-Glitch/goyave#24]
## Description

In my case, I want to customize my Http request error handler, for example the default 404 response is `404 page not found`. I need to customize it to a JSON response like 
```
{
 "error": true,
 "message": "Page not found",
 "code": 404
}
```

**Comment by System-Glitch** [comment]
Hello.

This is not yet possible but it is already planned for a future release.

**Comment by ervan23** [comment]
> Hello.
> 
> This is not yet possible but it is already planned for a future release.

Ok, can't wait for it. thx u
