### ISSUE TITLE
Social Media and Outreach Activities

### ISSUE THREAD

**Issue by marvinhosea** [System-Glitch/goyave#38]
## Description

Goyave is a very powerful framework but it is not reaching many gophers because you have not been leveraging social media and other platforms to reach developers.

### Possible drawbacks

Reach more Gophers and more contributors

## Additional information

I am a beginner in Golang and would love to contribute to this framework by promoting it to gophers.

**Comment by System-Glitch** [comment]
Hello,

Thank you for your feedback! Reaching more gophers and getting more contributors is far from a drawback.

I posted a few times on Reddit but not enough I think. What do you suggest?

At any rate, thank you very much for your proposal!

**Comment by marvinhosea** [comment]
Here are my suggestions and what I can help with.
1. Create a twitter account for social media updates.
2. Write a weekly blog
3. Weekly tweet on the progress, features, and updates
4. Welcome contributors to take part in the development
5. Help on StackOverflow
6. Being active on Reddit and other gophers community
7. Write sample application with Goyave
8. Contribute on the code when I can.

**Comment by System-Glitch** [comment]
I currently post the updates on my personal Twitter. Moving to a dedicated account is a good idea.

If you're willing to write a weekly blog and sample applications, please do!

I don't think anyone has asked any question about Goyave on StackOverflow yet (At least I can't find any). This is expected to happen if the framework grows in popularity though.

Let me know if you need any resource or information to do this, I will gladly help.

**Comment by marvinhosea** [comment]
Awesome, I will write the weekly blog post and sample applications and also tweet about it. It ok to close this issue. I will email for further communication
