### ISSUE TITLE
Failed to Dockerize

### ISSUE THREAD

**Issue by sopta** [System-Glitch/goyave#44]
## Description

**Version:** v2.7.0
**Environment:** Mac Os, 1.13
**Reproduces:** always

Hello,

There already was an issue called `Failed to Dockerize` which has been solved, but I've run into a different problem with dockerizing the goyave-template. It's important to note that everything works if it's running without Docker.

When I start a server, running inside a container, and I call /hello endpoint I get `curl: (52) Empty reply from server` response. When I start server just running by `go run goyave-template`, and I call /hello endpoint I get `Hi!` response.

I tried put logging inside `Start` function and I can see that the server is running. What interesting is that if I put logging inside the `SayHi` I got nothing in the terminal. So I suspect that the handler isn't even called. Also, I tried to use a closure. No success.

I haven't tried my Dockerize method with the prev version v2.2.0 in which the original issue was reported.

All files such as config.json, docker-compose and Dockerfile, are copy&paste in this description.

### How it occurred

```
Ghosts-MacBook-Pro-2:goyave-docker ghost$ curl -I localhost:8080/hello
curl: (52) Empty reply from server
```

**Expected result:**  
Based on the documentation, it should return `Hi!` message.

### How to reproduce

This is my **docker-compose.yml** file:

```
version: '3.2'

services:
  api:
    container_name: goyave_docker_api
    build: .
    ports:
      - 8080:8080

  vgo:
    container_name: goyave_docker_vgo
    image: golang:1.13
    volumes:
      - .:/app
    working_dir: /app
```

This is my **Dockerfile**:

```
FROM golang:1.13-alpine3.11 as builder

WORKDIR /app

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -mod=vendor -o api

FROM alpine:3.11

WORKDIR /app

RUN apk add --no-cache tzdata
RUN apk add --no-cache ca-certificates

ENV TZ Europe/Prague

COPY --from=builder /app/api ./api
COPY resources /app/resources
COPY config.json ./config.json

EXPOSE 8080

ENTRYPOINT [ "./api" ]
```

This is my **config.json** file:

```json
{
    "appName": "goyave-docker",
    "environment": "localhost",
    "domain": "",
    "maintenance": false,
    "host": "localhost",
    "port": 8080,
    "httpsPort": 8081,
    "protocol": "http",
    "tlsCert": "",
    "tlsKey": "",
    "debug": false,
    "timeout": 10,
    "maxUploadSize": 10,
    "defaultLanguage": "en-US",
    "dbConnection": "none",
    "dbHost": "127.0.0.1",
    "dbPort": 3306,
    "dbName": "goyave",
    "dbUsername": "root",
    "dbPassword": "root",
    "dbOptions": "charset=utf8&parseTime=true&loc=Local",
    "dbMaxOpenConnections": 20,
    "dbMaxIdleConnections": 20,
    "dbMaxLifetime": 300,
    "dbAutoMigrate": false
}
```

In the config.json, I changed `host` key from 127.0.0.1 to localhost.

Then I run:
1. `docker-compose run --rm vgo go get && go mod vendor` to create the vendor folder
2. `docker-compose up -d --build` to build an image a run a server

**Comment by System-Glitch** [comment]
Just to be sure, are you using curl from your host or from your container? Your config shows that your application is listening on `localhost` (or `127.0.0.1`) meaning that the it is only accessible from inside the container.

You have to change the `host` config entry to `0.0.0.0` if you want your application to be accessible from anywhere.

**Comment by sopta** [comment]
Hi,

oh my god, you're right. So far, I didn't have to set up the address, because it's handled by framework itself.

Thanks a lot 👍 You can close this issue.

**Comment by System-Glitch** [comment]
Take a look at [this gist](https://gist.github.com/System-Glitch/59a6e9e67783a29586eaa5a6dbfab3aa). It's a way of auto-restarting your application when you modify a file. It's especially useful for development!
