### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by Wulfheart** [System-Glitch/goyave#96]
Is there already an authentication system backed in? I couldn't find anything.

**Comment by System-Glitch** [comment]
https://system-glitch.github.io/goyave/guide/advanced/authentication.html

**Comment by Wulfheart** [comment]
But as far as I can see there is no csrf protection built-in. Am I correct?

**Comment by System-Glitch** [comment]
Indeed, CSRF is not needed for REST APIs because they dont use Cookies. If you want to add CSRF, you can use the [Gorilla CSRF package](https://github.com/gorilla/csrf) as a native middleware.
