### ISSUE TITLE
JSON body request example

### ISSUE THREAD

**Issue by sebastianmacias** [System-Glitch/goyave#97]
## Support

**Version:** v2.10.0

Can you please provide an example of a JSON body request controller with validation?

**Comment by sebastianmacias** [comment]
An example of unmarshaling a JSON body to an struct would be very helpful as well.

Thanks

**Comment by System-Glitch** [comment]
Hello. You don't have to do anything to handle both JSON and url-encoded forms, the framework does everything for you. The client has to set its `Content-Type` header so the framework can detect and parse the body correctly.

Here is an example:
`http/request/echorequest/echo.go`
```go
package echorequest

import "github.com/System-Glitch/goyave/v2/validation"

var (
	Echo validation.RuleSet = validation.RuleSet{
		"text": {"required", "string", "between:3,50"},
	}
)
``` 

`http/controller/hello/hello.go`
```go
package hello

import (
	"net/http"

	"github.com/System-Glitch/goyave/v2"
)

// Echo is a controller handler writing the input field "text" as a response.
// This route is validated. See "http/request/echorequest/echo.go" for more details.
func Echo(response *goyave.Response, request *goyave.Request) {
	response.String(http.StatusOK, request.String("text"))
}
```

`http/route/route.go`
```go
package route

import (
	"goyave_template/http/controller/hello"
	"goyave_template/http/request/echorequest"

	"github.com/System-Glitch/goyave/v2"
)

// Register all the application routes. This is the main route registrer.
func Register(router *goyave.Router) {
	router.Route("GET", "/echo", hello.Echo, echorequest.Echo)
}
```

The request body is put into a `map[string]interface{}`. If you want to get this data into a struct, you'll have to create the struct and fill it "manually":
```go
mystruct := &MyStruct{
	Field: response.String("text"),
}
```

Then, you can request it with the following curl command:
```
curl -H "Content-Type: application/json" -X POST -d '{"text":"Hello there!"}' http://localhost:8080/hello
```

This example is taken from the [Goyave template](https://github.com/System-Glitch/goyave-template).

**Comment by sebastianmacias** [comment]
Thank you
