### ISSUE TITLE
Gorm settings

### ISSUE THREAD

**Issue by Faboslav** [System-Glitch/goyave#98]
## Support

**Version:** v2.7.0

Hello, is there a way override basic Gorm settings in the global database connection scope, for example `auto_preload` feature?

**Comment by System-Glitch** [comment]
Hello!

`database.GetConnection()` returns `*gorm.DB`, so you can use it in the same way as you normally would.

I think you were think about this kind of setting ?

```go
database.GetConnection().Set("gorm:auto_preload", true)
```

You can make you configuration changes before starting the server:

```go
func configureDatabase() {
    db := database.GetConnection()
    db.Set("gorm:auto_preload", true)
    // Other settings...
}

func main() {
    configureDatabase()
    goyave.Start(route.Register)
}
```

**Comment by Faboslav** [comment]
Maybe i can handle it in some kind of middleware, because of the `database.Close()` thing, thank you for your response!
